apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: helloworld
spec:
  containers:
    - name: helloworld
      image: tutum/hello-world
      ports:
        - containerPort: 80
          name: myport # -----> ở đây
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
