apiVersion: v1
kind: Service
metadata:
  name: demo-healthcheck
spec:
  selector:
    app: demo-healthcheck
  ports:
    - name: mysvc
      protocol: TCP
      port: 80
      targetPort: myport
  type: LoadBalancer
