services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host
    ports:
      - "5173:5173"

  backend:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./backend:/app

  imgproxy:
    image: darthsim/imgproxy
